name: C compilation check
on:
  push:
      branches: [ '*' ]
  pull_request:
    branches: [ Adam☛☚ ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Branch name
      run: echo running on branch ${GITHUB_REF##*}
    - name: make
      run: make

  tests:

    runs-on: ubuntu-latest
    name: Unit tests
    steps:
    - uses: actions/checkout@v2
    - name: Branch name
      run: echo running on branch ${GITHUB_REF##*}
    - name: Run tests
      run: make test
